### ISSUE TITLE
Scene Clone Failed

### ISSUE THREAD

**Issue by anthonyrowe** [conix-center/ARENA-core#200]
Non-staff account still doesn't seem to be able to clone public scenes.  Burner account trying to clone anthony-office brings up "Scene Clone Failed!" popup. 

Console errors:
valid public public/anthony-office
/persist/anthony/office:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
scenes.js:202 Error: Request failed with status code 401
    at e.exports (isAxiosError.js:10)
    at e.exports (isAxiosError.js:10)
    at XMLHttpRequest.l.onreadystatechange (isAxiosError.js:10)
/persist/anthony/office:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
scenes.js:202 Error: Request failed with status code 401
    at e.exports (isAxiosError.js:10)
    at e.exports (isAxiosError.js:10)
    at XMLHttpRequest.l.onreadystatechange (isAxiosError.js:10)

**Comment by mwfarb** [comment]
I think this is from the user/scenes page using the last cached mqtt_token for the persist call which was likely from another page, if at all. My guess is this page needs a new mqtt_token requested with permissions specific to general account operations. I'll check that.

**Comment by mwfarb** [comment]
Two solutions required:
1. Added `public` namespace subscription rights for all anon and auth users for all mqtt tokens genrated: https://github.com/conix-center/arena-account/pull/23. This will help for those who visit a build/network/arts/scene page first, however...
2. If a user hasn't visited a page that calls `/user/mqtt_auth`, then they still will get this error because they would have no mqtt token to pass to `/persist`. For arena-account pages like `/user/scenes` they should probably build an internal token.

**Comment by mwfarb** [comment]
Ok, Solution 2 now added: https://github.com/conix-center/arena-account/commit/2440885990d2b0e574831c06e1318c88bb7efe8e.
