### ISSUE TITLE
Can A/V in background tabs be improved?

### ISSUE THREAD

**Issue by mwfarb** [conix-center/ARENA-core#202]
- Understand Keep Alives with Background Tabs… 
- Thoughtline 2/17 (ivan)

**Comment by hiliang-cmu** [comment]
The webGL canvas will not work in general to any aframe `tick()` behavior due to general browser behavior of ceasing `requestAnimationFrame()`

As such, mostly resolved with `a0f21bc`. Only caveat: 

The above 'fix' by means of an external interval, follows behavior of the current heartbeat while tab is active, which is an `update` action, not a `create`.
