### ISSUE TITLE
Fix microphone A/V setup test for Chrome/Safari

### ISSUE THREAD

**Issue by mwfarb** [conix-center/ARENA-core#212]
- Current mic test https://github.com/cwilso/volume-meter/ and https://webaudiodemos.appspot.com/volume-meter/.
- Works for me on macos desktop firefox, but not macos desktop chrome or safari.

**Comment by mwfarb** [comment]
OK, seems like this is working chrome for some others and it's just my machine?

**Comment by mwfarb** [comment]
Seems to tun off when

**Comment by mwfarb** [comment]
Loading links in a new tab helps: https://github.com/conix-center/ARENA-core/commit/e7e14a5d8ebde98d5ba5afb54cd4e378b8557d43

**Comment by hiliang-cmu** [comment]
Not sure this is 100% related to this specifically, but there are some weirdness with browser navigating/refreshing some of the UI pages page, since the selected fields will keep to whatever you had them as (without triggering select `change` events).

For example, when you choose one of the dropdowns, the handler on change sets that selected device-id as active mic input. If you nav back and forth, the av page may load without the input device set.
