### ISSUE TITLE
Per scene options

### ISSUE THREAD

**Issue by nampereira** [conix-center/ARENA-core#49]
We have a global defaults object with some parameters that could be per-scene settings, like `themeParam`, `weatherParam`. Some of these are also defaults of the URL parameters we receive.

Additionally, we have some settings that could be defined per scene, like the **bigscreen name**, or the **jitsi server**, and possibly other. 

As we discussed, we could add a scene options/settings object to persist. It could look like this:

```
{
  "object_id": "myscene_options",
  "action": "create",
  "persist": true,
  "type": "scene-options",
  "data": {
     themeParam:"starry",
     weatherParam:"none",
     bigscreen: "bigscreen",
     jitsi-server: "mr.andrew.cmu.edu"
  }
}
```
**Any thoughts? What should be here or not ?**

(I realize this would allow multiple options objects to exist in a scene; in my mind, that is not a big deal)

**Comment by hiliang-cmu** [comment]
- Can add either a separate route, or make current persistence per-scene GET call order the options first

- Could push access control to MQTT,  move messaging for these scene settings to a separate topic tree, e.g. `realm/sc/scenename` that restricts write appropriately

**Comment by nampereira** [comment]
Both make sense. Could/should we constraint a scene to have only one of these objects?

**Comment by nampereira** [comment]
Cool. Maybe do the uniqueness on the `"type": "scene-options"` ?

**Comment by hiliang-cmu** [comment]
I kinda pushed the "constraint" behavior to the `object_id` because current collection setup doesn't actually have a real database "unique" constraint at all. It just keys all create/updates/deletes based on `object_id` (per scene), so attempting to create/modify a duplicate just ends up mutating the same record. 

This is mainly because persistence doesn't have a means of response unlike an HTTP API for example. So adding and violating an actual database constraint (e.g. set mongo `object_id` index to `unique`, then attempt to create an object_id that already exists) would result only silent failures.

> do the uniqueness on the "type": "scene-options" ?

So per the above, uniqueness would not be a database constraint. It'd have to be added via new conditional statements based `type` which currently is not a thing yet...I'm less enthusiastic about this unless there are any other `types` that might need additional handling.

**Comment by nampereira** [comment]
Gotcha. Unique on object id works for me.

**Comment by hiliang-cmu** [comment]
Per discussion, current persistence HTTP API allows for `type` filtering. Accordingly, multiple `object_id`'s with `"type": "settings"` could be added per scene. It should be up to the client to GET first `/persist/:sceneId?type=settings` then `/persist/:sceneId?type=object` etc....

**Comment by mwfarb** [comment]
For schema, maybe it should follow the env element of https://github.com/supermedium/aframe-environment-component?

**Comment by nampereira** [comment]
Yes! Great find!

**Comment by mwfarb** [comment]
We should also add a boolean for `clickableOnlyEvents`, default to `true` for publishing only mouse events for objects with click-listeners (current), and for `false` all objects would publish mouse events. To be used by https://github.com/conix-center/ARENA-core/issues/43 .

**Comment by nampereira** [comment]
Add a `privateScene` default to `false`.

**Comment by mwfarb** [comment]
:+1: for `privateScene`
